### ISSUE TITLE
h3_to_parent at resolution 0 labels it as direct parent

### ISSUE THREAD

**Issue by alpha-beta-soup** [DahnJ/H3-Pandas#15]
`h3_to_parent` at resolution 0 calculates correctly, but returns a column called  `h3_parent`, rather than `h3_00` (or perhaps `h3_0`?) as expected based on the pattern for other resolutions.

I don't think there's anything unexpected about calculating the 0-level parent (I use it for partitioning; a higher resolution is used for my actual information). Rather it's just that [this line](https://github.com/DahnJ/H3-Pandas/blob/master/h3pandas/h3pandas.py#L331) checks for implicit False, not a strict check for None.

`column = self._format_resolution(resolution) if resolution else "h3_parent"`

Should be:

`column = self._format_resolution(resolution) if resolution != None else "h3_parent"`

```
>>> 'a' if 0 != None else 'b'
'a'
>>> 'a' if 0 else 'b'
'b'
```

The actual result is correct, it is a level-0 cell.

**Comment by DahnJ** [comment]
Hi @alpha-beta-soup, thank you for the bug report and for finding the solution! I implemented the change in https://github.com/DahnJ/H3-Pandas/pull/21
