### ISSUE TITLE
Q: Multicore support?

### ISSUE THREAD

**Issue by diehl** [DahnJ/H3-Pandas#28]
When performing polyfill operations, does H3-Pandas currently utilize multiple cores?

**Comment by DahnJ** [comment]
Hi @diehl in general the answer is no, H3-Pandas only adds h3-related functionality to [Pandas](https://pandas.pydata.org/docs/index.html) Dataframes and as such does not suport concurrency.

However, you can use [Dask](https://docs.dask.org/en/stable/dataframe.html) and [Dask-Geopandas](https://dask-geopandas.readthedocs.io/en/stable/) to achieve this fairly easily. See the section "Dask-GeoPandas example" in [this example](https://github.com/DahnJ/H3-Pandas/issues/27#issuecomment-1924874322).

**Comment by diehl** [comment]
Thanks @DahnJ - That is exactly the route I'm heading down now. Going to use Coiled to parallelize the computation in the cloud.

**Comment by DahnJ** [comment]
Sounds good!

By the way, with Dask distributed, you don't need to embed the import into your functions: since you have a stable set of workers, you can simply `import h3pandas` once on them after startup.

Sample code

```python
from dask.distributed import Client

client = Client()

def import_h3pandas():
    import h3pandas

client.run(import_h3pandas)
```

**Comment by diehl** [comment]
I appreciate that pointer @DahnJ!
